task: estqa_cot_fewshot
dataset_path: TalTechNLP/EstQA
output_type: generate_until
validation_split: train
test_split: test
fewshot_config: #do not specify fewshot_split if you take samples from utils 
  sampler: first_n 
  samples: !function utils.list_fewshot_samples
description: "Given a passage and a question, choose the excerpt from the passage that answers the question.\n\n"
doc_to_text: !function utils.doc_to_text_cot_oneshot
doc_to_target: '{{answers[0]["text"]}}'
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_punctuation: true
generation_kwargs:
  until:
    - "</s>"
    - "<|end_of_text|>"
    - "\n\n"
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "Therefore, the answer in Estonian is \"([^\"]*)\""
      - function: "take_first"
metadata:
  version: 1.0