task: estqa_fewshot_gen
dataset_path: TalTechNLP/EstQA
output_type: generate_until
validation_split: train
test_split: test
fewshot_config: #do not specify fewshot_split if you take samples from utils 
  sampler: first_n
  samples: !function utils.list_fewshot_samples
description: "Given a passage and a question, choose the excerpt from the passage that answers the question.\n\n"
doc_to_text: "Title: {{title}}\nPassage: {{context}}\nQuestion: {{question}}\nAnswer:"
doc_to_target: '{{answers[0]["text"]}}'
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_punctuation: true
    ignore_case: true
generation_kwargs:
  until:
    - "</s>"
    - "<|end_of_text|>"
    - "\n\n"
filter_list:
  - name: "remove_whitespace"
    filter:
      - function: remove_whitespace
      - function: "take_first" #must be set, otherwise list is returned
metadata:
  version: 1.0