task: tydiqa_fi_fewshot_cot
dataset_path: smugri-lm-eval-configs/data/tydiqa-fi
output_type: generate_until
test_split: test
fewshot_config: #do not specify fewshot_split if you take samples with utils 
  sampler: first_n 
  samples: !function utils.list_fewshot_samples
description: "Given a passage and a question, choose the excerpt from the passage that answers the question.\n\n"
doc_to_text: !function utils.doc_to_text_cot_oneshot
doc_to_target: '{{answers["text"][0]}}'
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_punctuation: false
generation_kwargs:
  until:
    - "</s>"
    - "<|end_of_text|>"
    - "\n\n"
filter_list:
  - name: "strict-match"
    filter:
      - function: "regex"
        regex_pattern: "Therefore, the answer in Finnish is \"([^\"]*)\""
      - function: "take_first"
metadata:
  version: 1.0