task: tydiqa_fi_fewshot_gen
dataset_path: smugri-lm-eval-configs/data/tydiqa-fi
output_type: generate_until
fewshot_split: train
fewshot_config:
  sampler: first_n
test_split: test
description: "Given a passage and a question, choose the excerpt from the passage that answers the question.\n\n"
doc_to_text: "Title: {{title}}\nPassage: {{context}}\nQuestion: {{question}}\nAnswer:"
doc_to_target: '{{answers["text"][0]}}'
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_punctuation: false
    ignore_case: true
generation_kwargs:
  until:
    - "</s>"
    - "<|end_of_text|>"
    - "\n\n"
filter_list:
  - name: "remove_whitespace"
    filter:
      - function: remove_whitespace
      - function: "take_first" #must be set
metadata:
  version: 1.0