"dataset_name": "rus_Cyrl-kpv_Cyrl"
"description": "Translate the text from Russian to Komi.\n\n"
"doc_to_decontamination_query": "{{sentence_rus_Cyrl}}\t{{sentence_kpv_Cyrl}}"
"doc_to_target": "{{sentence_kpv_Cyrl}}"
"doc_to_text": "Russian: {{sentence_rus_Cyrl}}\nKomi:"
"include": "_default_template_yaml"
"task": "flores_smugri_rus_Cyrl-kpv_Cyrl"
