"dataset_name": "rus_Cyrl-liv_Latn"
"description": "Translate the text from Russian to Livonian.\n\n"
"doc_to_decontamination_query": "{{sentence_rus_Cyrl}}\t{{sentence_liv_Latn}}"
"doc_to_target": "{{sentence_liv_Latn}}"
"doc_to_text": "Russian: {{sentence_rus_Cyrl}}\nLivonian:"
"include": "_default_template_yaml"
"task": "flores_smugri_rus_Cyrl-liv_Latn"
