"dataset_name": "eng_Latn-vro_Latn"
"description": "Translate the text from English to Võro.\n\n"
"doc_to_decontamination_query": "{{sentence_eng_Latn}}\t{{sentence_vro_Latn}}"
"doc_to_target": "{{sentence_vro_Latn}}"
"doc_to_text": "English: {{sentence_eng_Latn}}\nVõro:"
"include": "_default_template_yaml"
"task": "flores_smugri_eng_Latn-vro_Latn"
