task: xcopa_et_fewshot
dataset_path: xcopa
dataset_name: et
description: "Given a premise and a prompt, select the more meaningful of the two choices.\n\n"
output_type: multiple_choice
test_split: test
fewshot_config: #do not specify fewshot_split if you take samples with utils 
  sampler: first_n 
  samples: !function utils.list_fewshot_samples
doc_to_text: !function utils.doc_to_text
doc_to_target: label
doc_to_choice: !function utils.doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
